version: '3'

services:

    ################
    ##### TEST #####
    ################
    super_test:
        build: ./superdocker
        image: super:master

        depends_on:
            - db_test
            - front_test
        volumes:
            - ./superdocker/test/ExpressJS-Study:/home/api

        ports:
            - "30200:3000"

        command:
            - /bin/bash
            - -c
            - |
                cd /home/api/API/11st
                npm install && npm run build
                cd ../joongna
                npm install && npm run build
                cd ../../express-for-typescript
                npm install && npm run build && npm start

    db_test:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secure

    front_test:
        build: ./frontdocker
        image: front:test

        #volumes:
        #    - ./frontdocker/biccon.github.io:/home/front

        ports:
            - "30280:80"

        command:
            - /bin/bash
            - -c
            - |
                cp -r /home/front/* /usr/share/nginx/html/
                cat /usr/share/nginx/html
                nginx -g "daemon off;"

    ##################
    ##### STABLE #####
    ##################
    api:
        build: ./apidocker
        image: api:master

        volumes:
            - ./apidocker/master/ExpressJS-Study:/home/api
        ports:
            - "30001:3000"
        command:
            - /bin/bash
            - -c
            - |
                cd /home/api/API/11st
                npm install && npm run build
                cd ../joongna
                npm install && npm run build
                cd ../../express-for-typescript
                npm install && npm run build && npm start