version: '3'

services:

    ################
    ##### TEST #####
    ################
    super_test:
        build: ./superdocker
        image: super:test

        #depends_on:
        #    - front_test
        volumes:
            - ~/Product/Main_Server:/home/Main_Server
        ports:
            - "30100:3002"

        command:
            - /bin/bash
            - -c
            - |
                cd /home/Main_Server
                npm install && npm run build
                npm run copy-view && npm start
                #cd ../../test_api/joongna
                #npm install && npm run build
                #cd ..
                #npm install && npm run dev

    front_test:
        build: ./frontdocker
        image: front:test2
                #service nginx reload

        volumes:
            - ~/Product/Layout:/home/Layout

        ports:
            - "30300:3000"

        command:
            - /bin/bash
            - -c
            - |
                cd /home/Layout
                npm install && npm start
                

    ##################
    ##### STABLE #####
    ##################
    super:
        build: ./superdocker
        image: super:stable

        volumes:
            - ~/Test_Product/Main_Server:/home/Main_Server
        ports:
            - "30001:3002"
        command:
            - /bin/bash
            - -c
            - |
                cd /home/Main_Server
                npm install && npm run build
                npm run copy-view && npm start
    front:
        build: ./frontdocker
        image: front:stable

        volumes:
            - ~/Test_Product/Layout:/home/Layout
        ports:
            - "30000:3000"
        command:
            - /bin/bash
            - -c
            - |
                cd /home/Layout
                npm install && npm start