name: Deploy

on:
  pull_request:
    branches:
      - s5kywa1k3r_deploy

jobs:
  Deployment:
    runs-on: ubuntu-latest
    # Run only on non-merged non-draft mergeable pull requests    
    if: |
      !(
        (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
        && !github.event.pull_request.draft
        && !github.event.pull_request.merged
        && github.event.pull_request.merge_commit_sha != null
      )
      
    steps:
      - name: Checkout a Git repository at a particular version
        uses: actions/checkout@v2
         with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      
      - name: Test
        run: |
          ls -al
          pwd
          echo hello merged i will deploy!