name: Front Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - 'Layout/**'

jobs:
  Front_Deployment:
    runs-on: ubuntu-latest
    # Run only on merged pull requests
    if: |
      github.event.pull_request.merged && 
      github.event.pull_request.merge_commit_sha != null
      
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/Test_Product
            git pull origin master
            
            cd Server/Docker
            docker-compose up -d front