name: lint.yml

on: 
  push: # push의 경우에만 실행한다.
    branches: 
      - s5kywa1k3r_deploy # master branch에만 발생했을 경우 실행한다.

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        # with:
        #   files: src/
